volumes:
  pgh3-poc-bornes:

services:
  db:
    image: crazycapivara/postgres-postgis:10-pgh3
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgh3-poc-bornes:/var/lib/postgresql/data
      - ./geodata:/geodata
    ports:
      - 5598:5432

  setup_db_ext:
    image: ubuntu/postgres
    depends_on:
      - db
    command: |
      /bin/bash -c
        "sleep 3 && \
        PGPASSWORD=mypassword psql -U postgres -h db postgres -c 'create extension IF NOT EXISTS postgis; create extension IF NOT EXISTS pgh3;'"

  osgeo:
    build:
      context: .
      dockerfile: osgeo.Dockerfile
    environment:
      EPSG_CODE: 4326
    depends_on:
      - db
    volumes:
      - ./geodata:/geodata
      - ./etl:/etl
    command: alembic upgrade head