volumes:
  pgh3-poc-bornes:

services:
  db:
    image: crazycapivara/postgres-postgis:10-pgh3
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
    volumes:
      - pgh3-poc-bornes:/var/lib/postgresql/data
      - ./geodata:/geodata
    ports:
      - 5598:5432

  osgeo:
    image: osgeo/gdal:ubuntu-small-latest
    environment:
      EPSG_CODE: 4326
    depends_on:
      - db
    volumes:
      - ./geodata:/geodata
      - ./etl:/etl
